name: Non-OMV-tests

on:
  push:
    branches: [ main, development, experimental, ow* ]
  pull_request:
    branches: [ main, development, experimental, ow* ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        runs-on: [ubuntu-latest ]
        python-version: [ 3.9, "3.10" ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version:  ${{ matrix.python-version }}

        
    - name: Install OMV
      run: |
        pip install git+https://github.com/OpenSourceBrain/osb-model-validation
        
    - name: Install pyNeuroML
      run: |
        omv install pyNeuroML
        
        
    - name: Run test script
      run: |
        ./test_all.sh
        
    - name: Final version info
      run: |
        pip list
        env
